name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: windows-2019
    steps:
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
      - shell: bash
        run: |
          clang --version
          cmake --version || echo NOOO cmake
          ninja --version || echo NOO ninja
          cc --version
